using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

namespace Argo.DataAnalysis;

public class ZDOInfo
{
    public readonly Dictionary<int, string> HashToName;
    public readonly List<int>               Hashes;
    public static string GetName(int hash) {
        if (instance != null && instance.HashToName.TryGetValue( hash, out var name )) {
            return name;
        }
        return "";
    }
    private ZDOInfo() {
        HashToName=GetNames();
        Hashes    =MakeHashList();
    }

    private static ZDOInfo? instance;
    public static  ZDOInfo  Instance { get => instance??=new ZDOInfo(); }

    private static Type GetZdoType(Player player, int hash) {
        ZDOID      zdoID=player.GetZDOID();
        float      s_floats;
        Vector3    s_vec3;
        Quaternion s_quats;
        int        s_ints;
        long       s_longs;
        string     s_strings;
        byte[]     s_byteArrays;
        Type       type=typeof(void);
        return type; // todo, might not be possible
    }
    private static Dictionary<int, string> GetNames() {
        Dictionary<int, string> dict=new Dictionary<int, string>();
        dict[ "0_item".GetStableHashCode()] = "0_item" ;
        dict[ "1_item".GetStableHashCode()] = "1_item" ;
        dict[ "2_item".GetStableHashCode()] = "2_item" ;
        dict[ "3_item".GetStableHashCode()] = "3_item" ;
        dict[ "4_item".GetStableHashCode()] = "4_item" ;
        dict[ "5_item".GetStableHashCode()] = "5_item" ;
        dict[ "6_item".GetStableHashCode()] = "6_item" ;
        dict[ "7_item".GetStableHashCode()] = "7_item" ;
        dict[ "0_variant".GetStableHashCode()] = "0_variant" ;
        dict[ "1_variant".GetStableHashCode()] = "1_variant" ;
        dict[ "2_variant".GetStableHashCode()] = "2_variant" ;
        dict[ "3_variant".GetStableHashCode()] = "3_variant" ;
        dict[ "4_variant".GetStableHashCode()] = "4_variant" ;
        dict[ "5_variant".GetStableHashCode()] = "5_variant" ;
        dict[ "6_variant".GetStableHashCode()] = "6_variant" ;
        dict[ "7_variant".GetStableHashCode()] = "7_variant" ;
        dict[ "0_quality".GetStableHashCode()] = "0_quality" ;
        dict[ "1_quality".GetStableHashCode()] = "1_quality" ;
        dict[ "2_quality".GetStableHashCode()] = "2_quality" ;
        dict[ "3_quality".GetStableHashCode()] = "3_quality" ;
        dict[ "4_quality".GetStableHashCode()] = "4_quality" ;
        dict[ "5_quality".GetStableHashCode()] = "5_quality" ;
        dict[ "6_quality".GetStableHashCode()] = "6_quality" ;
        dict[ "7_quality".GetStableHashCode()] = "7_quality" ;
        dict[ "ShoulderItemQuality".GetStableHashCode()] = "ShoulderItemQuality" ;
        dict[ "LegItemVariant".GetStableHashCode()] = "LegItemVariant" ;
        dict[ "LegItemQuality".GetStableHashCode()] = "LegItemQuality" ;
        dict[ "ChestItemVariant".GetStableHashCode()] = "ChestItemVariant" ;
        dict[ "HelmetItemVariant".GetStableHashCode()] = "HelmetItemVariant" ;
        dict[ "RightBackItemVariant".GetStableHashCode()] = "RightBackItemVariant" ;
        dict[ "RightItemVariant".GetStableHashCode()] = "RightItemVariant" ;
        dict[ "ChestItemQuality".GetStableHashCode()] = "ChestItemQuality" ;
        dict[ "HelmetItemQuality".GetStableHashCode()] = "HelmetItemQuality" ;
        dict[ "RightBackItemQuality".GetStableHashCode()] = "RightBackItemQuality" ;
        dict[ "RightItemQuality".GetStableHashCode()] = "RightItemQuality" ;
        dict[ "LeftBackItemQuality".GetStableHashCode()] = "LeftBackItemQuality" ;
        dict[ "LeftItemQuality".GetStableHashCode()] = "LeftItemQuality" ;
        dict[ ZDOVars.s_worldLevel] = "worldLevel" ;
        dict[ ZDOVars.s_pickedUp] = "pickedUp" ;
        dict[ ZDOVars.s_roomData] = "roomData" ;
        dict[ ZDOVars.s_TCData] = "TCData" ;
        dict[ ZDOVars.s_accTime] = "accTime" ;
        dict[ ZDOVars.s_addedDefaultItems] = "addedDefaultItems" ;
        dict[ ZDOVars.s_aggravated] = "aggravated" ;
        dict[ ZDOVars.s_alert] = "alert" ;
        dict[ ZDOVars.s_aliveTime] = "alive_time" ;
        dict[ ZDOVars.s_ammo] = "ammo" ;
        dict[ ZDOVars.s_ammoType] = "ammoType" ;
        dict[ ZDOVars.s_attachJointHash] = "attachJoint" ;
        dict[ ZDOVars.s_author] = "author" ;
        dict[ ZDOVars.s_authorDisplayName] = "authorPlatformDisplayName" ;
        dict[ ZDOVars.s_bait] = "Bait" ;
        dict[ ZDOVars.s_bakeTimer] = "bakeTimer" ;
        dict[ ZDOVars.s_baseValue] = "baseValue" ;
        dict[ ZDOVars.s_beardItem] = "BeardItem" ;
        dict[ ZDOVars.s_bodyAVelHash] = "body_avel" ;
        dict[ ZDOVars.s_bodyVelHash] = "body_vel" ;
        dict[ ZDOVars.s_bodyVelocity] = "BodyVelocity" ;
        dict[ ZDOVars.s_catchID] = "catchID" ;
        dict[ ZDOVars.s_chestItem] = "ChestItem" ;
        dict[ ZDOVars.s_content] = "Content" ;
        dict[ ZDOVars.s_crafterID] = "crafterID" ;
        dict[ ZDOVars.s_crafterName] = "crafterName" ;
        dict[ ZDOVars.s_creator] = "creator" ;
        dict[ ZDOVars.s_creatorName] = "creatorName" ;
        dict[ ZDOVars.s_data] = "data" ;
        dict[ ZDOVars.s_dataCount] = "dataCount" ;
        dict[ ZDOVars.s_dead] = "dead" ;
        dict[ ZDOVars.s_debugFly] = "DebugFly" ;
        dict[ ZDOVars.s_despawnInDay] = "DespawnInDay" ;
        dict[ ZDOVars.s_dodgeinv] = "dodgeinv" ;
        dict[ ZDOVars.s_done] = "done" ;
        dict[ ZDOVars.s_drops] = "drops" ;
        dict[ ZDOVars.s_durability] = "durability" ;
        dict[ ZDOVars.s_eitr] = "eitr" ;
        dict[ ZDOVars.s_emote] = "emote" ;
        dict[ ZDOVars.s_emoteID] = "emoteID" ;
        dict[ ZDOVars.s_emoteOneshot] = "emote_oneshot" ;
        dict[ ZDOVars.s_enabled] = "enabled" ;
        dict[ ZDOVars.s_escape] = "escape" ;
        dict[ ZDOVars.s_eventCreature] = "EventCreature" ;
        dict[ ZDOVars.s_follow] = "follow" ;
        dict[ ZDOVars.s_forward] = "forward" ;
        dict[ ZDOVars.s_fuel] = "fuel" ;
        dict[ ZDOVars.s_growStart] = "GrowStart" ;
        dict[ ZDOVars.s_hairColor] = "HairColor" ;
        dict[ ZDOVars.s_hairItem] = "HairItem" ;
        dict[ ZDOVars.s_haveSaddleHash] = "HaveSaddle" ;
        dict[ ZDOVars.s_haveTargetHash] = "haveTarget" ;
        dict[ ZDOVars.s_health] = "health" ;
        dict[ ZDOVars.s_helmetItem] = "HelmetItem" ;
        dict[ ZDOVars.s_hitDir] = "HitDir" ;
        dict[ ZDOVars.s_hitPoint] = "HitPoint" ;
        dict[ ZDOVars.s_hooked] = "hooked" ;
        dict[ ZDOVars.s_hue] = "Hue" ;
        dict[ ZDOVars.s_huntPlayer] = "huntplayer" ;
        dict[ ZDOVars.s_inBed] = "inBed" ;
        dict[ ZDOVars.s_inUse] = "InUse" ;
        dict[ ZDOVars.s_inWater] = "inWater" ;
        dict[ ZDOVars.s_initVel] = "InitVel" ;
        dict[ ZDOVars.s_isBlockingHash] = "IsBlocking" ;
        dict[ ZDOVars.s_item] = "item" ;
        dict[ ZDOVars.s_item0] = "item0" ;
        dict[ ZDOVars.s_itemPrefab] = "itemPrefab" ;
        dict[ ZDOVars.s_itemStack] = "itemStack" ;
        dict[ ZDOVars.s_items] = "items" ;
        dict[ ZDOVars.s_landed] = "landed" ;
        dict[ ZDOVars.s_lastAttack] = "lastAttack" ;
        dict[ ZDOVars.s_lastSpawn] = "LastSpawn" ;
        dict[ ZDOVars.s_lastTime] = "lastTime" ;
        dict[ ZDOVars.s_leftBackItem] = "LeftBackItem" ;
        dict[ ZDOVars.s_leftBackItemVariant] = "LeftBackItemVariant" ;
        dict[ ZDOVars.s_leftItem] = "LeftItem" ;
        dict[ ZDOVars.s_leftItemVariant] = "LeftItemVariant" ;
        dict[ ZDOVars.s_legItem] = "LegItem" ;
        dict[ ZDOVars.s_level] = "level" ;
        dict[ ZDOVars.s_liquidData] = "LiquidData" ;
        dict[ ZDOVars.s_location] = "location" ;
        dict[ ZDOVars.s_lookTarget] = "LookTarget" ;
        dict[ ZDOVars.s_locked] = "Locked" ;
        dict[ ZDOVars.s_lovePoints] = "lovePoints" ;
        dict[ ZDOVars.s_maxHealth] = "max_health" ;
        dict[ ZDOVars.s_maxInstances] = "MaxInstances" ;
        dict[ ZDOVars.s_modelIndex] = "ModelIndex" ;
        dict[ ZDOVars.s_noise] = "noise" ;
        dict[ ZDOVars.s_offset] = "offset" ;
        dict[ ZDOVars.s_owner] = "owner" ;
        dict[ ZDOVars.s_ownerName] = "ownerName" ;
        dict[ ZDOVars.s_patrol] = "patrol" ;
        dict[ ZDOVars.s_patrolPoint] = "patrolPoint" ;
        dict[ ZDOVars.s_permitted] = "permitted" ;
        dict[ ZDOVars.s_pickable] = "pickable" ;
        dict[ ZDOVars.s_picked] = "picked" ;
        dict[ ZDOVars.s_pickedTime] = "picked_time" ;
        dict[ ZDOVars.s_piece] = "piece" ;
        dict[ ZDOVars.s_plantTime] = "plantTime" ;
        dict[ ZDOVars.s_played] = "played" ;
        dict[ ZDOVars.s_playerID] = "playerID" ;
        dict[ ZDOVars.s_playerName] = "playerName" ;
        dict[ ZDOVars.s_plays] = "plays" ;
        dict[ ZDOVars.s_pose] = "pose" ;
        dict[ ZDOVars.s_pregnant] = "pregnant" ;
        dict[ ZDOVars.s_product] = "product" ;
        dict[ ZDOVars.s_pvp] = "pvp" ;
        dict[ ZDOVars.s_quality] = "quality" ;
        dict[ ZDOVars.s_queued] = "queued" ;
        dict[ ZDOVars.s_randomSkillFactor] = "RandomSkillFactor" ;
        dict[ ZDOVars.s_relPosHash] = "relPos" ;
        dict[ ZDOVars.s_relRotHash] = "relRot" ;
        dict[ ZDOVars.s_rightBackItem] = "RightBackItem" ;
        dict[ ZDOVars.s_rightItem] = "RightItem" ;
        dict[ ZDOVars.s_rodOwner] = "rodOwner" ;
        dict[ ZDOVars.s_rooms] = "rooms" ;
        dict[ ZDOVars.s_rudder] = "rudder" ;
        dict[ ZDOVars.s_saturation] = "Saturation" ;
        dict[ ZDOVars.s_scaleHash] = "scale" ;
        dict[ ZDOVars.s_scaleScalarHash] = "scaleScalar" ;
        dict[ ZDOVars.s_seAttrib] = "seAttrib" ;
        dict[ ZDOVars.s_seed] = "seed" ;
        dict[ ZDOVars.s_shoulderItem] = "ShoulderItem" ;
        dict[ ZDOVars.s_shoulderItemVariant] = "ShoulderItemVariant" ;
        dict[ ZDOVars.s_shownAlertMessage] = "ShownAlertMessage" ;
        dict[ ZDOVars.s_skinColor] = "SkinColor" ;
        dict[ ZDOVars.s_sleeping] = "sleeping" ;
        dict[ ZDOVars.s_spawnAmount] = "SpawnAmount" ;
        dict[ ZDOVars.s_spawnOre] = "SpawnOre" ;
        dict[ ZDOVars.s_spread] = "spread" ;
        dict[ ZDOVars.s_stack] = "stack" ;
        dict[ ZDOVars.s_stamina] = "stamina" ;
        dict[ ZDOVars.s_startTime] = "StartTime" ;
        dict[ ZDOVars.s_state] = "state" ;
        dict[ ZDOVars.s_stealth] = "Stealth" ;
        dict[ ZDOVars.s_support] = "support" ;
        dict[ ZDOVars.s_tag] = "tag" ;
        dict[ ZDOVars.s_tagauthor] = "tagauthor" ;
        dict[ ZDOVars.s_tameLastFeeding] = "TameLastFeeding" ;
        dict[ ZDOVars.s_tameTimeLeft] = "TameTimeLeft" ;
        dict[ ZDOVars.s_tamed] = "tamed" ;
        dict[ ZDOVars.s_tamedName] = "TamedName" ;
        dict[ ZDOVars.s_tamedNameAuthor] = "TamedNameAuthor" ;
        dict[ ZDOVars.s_targets] = "targets" ;
        dict[ ZDOVars.s_text] = "text" ;
        dict[ ZDOVars.s_tiltrot] = "tiltrot" ;
        dict[ ZDOVars.s_timeOfDeath] = "timeOfDeath" ;
        dict[ ZDOVars.s_triggered] = "triggered" ;
        dict[ ZDOVars.s_type] = "type" ;
        dict[ ZDOVars.s_user] = "user" ;
        dict[ ZDOVars.s_utilityItem] = "UtilityItem" ;
        dict[ ZDOVars.s_value] = "Value" ;
        dict[ ZDOVars.s_variant] = "variant" ;
        dict[ ZDOVars.s_velHash] = "vel" ;
        dict[ ZDOVars.s_wakeup] = "wakeup" ;
        dict[ ZDOVars.s_weaponLoaded] = "WeaponLoaded" ;
        dict[ ZDOVars.s_worldTimeHash] = "lastWorldTime" ;
        dict[ ZDOVars.s_visual] = "visual" ;
        dict[ ZDOVars.s_terrainModifierTimeCreated] = "terrainModifierTimeCreated" ;
        dict[ ZDOVars.s_spawnPoint] = "spawnpoint" ;
        dict[ ZDOVars.s_SpawnPoint__DontUse] = "SpawnPoint" ;
        dict[ ZDOVars.s_spawnTime] = "spawntime" ;
        dict[ ZDOVars.s_SpawnTime__DontUse] = "SpawnTime" ;
        dict[ ZDOVars.s_spawn_time__DontUse] = "spawn_time" ;
        return dict;
    }
    private static List<int> MakeHashList() {
        List<int> list= [];
        list.Add( ZDOVars.s_worldLevel);
        list.Add( ZDOVars.s_pickedUp);
        list.Add( ZDOVars.s_roomData);
        list.Add( ZDOVars.s_TCData);
        list.Add( ZDOVars.s_accTime);
        list.Add( ZDOVars.s_addedDefaultItems);
        list.Add( ZDOVars.s_aggravated);
        list.Add( ZDOVars.s_alert);
        list.Add( ZDOVars.s_aliveTime);
        list.Add( ZDOVars.s_ammo);
        list.Add( ZDOVars.s_ammoType);
        list.Add( ZDOVars.s_attachJointHash);
        list.Add( ZDOVars.s_author);
        list.Add( ZDOVars.s_authorDisplayName);
        list.Add( ZDOVars.s_bait);
        list.Add( ZDOVars.s_bakeTimer);
        list.Add( ZDOVars.s_baseValue);
        list.Add( ZDOVars.s_beardItem);
        list.Add( ZDOVars.s_bodyAVelHash);
        list.Add( ZDOVars.s_bodyVelHash);
        list.Add( ZDOVars.s_bodyVelocity);
        list.Add( ZDOVars.s_catchID);
        list.Add( ZDOVars.s_chestItem);
        list.Add( ZDOVars.s_content);
        list.Add( ZDOVars.s_crafterID);
        list.Add( ZDOVars.s_crafterName);
        list.Add( ZDOVars.s_creator);
        list.Add( ZDOVars.s_creatorName);
        list.Add( ZDOVars.s_data);
        list.Add( ZDOVars.s_dataCount);
        list.Add( ZDOVars.s_dead);
        list.Add( ZDOVars.s_debugFly);
        list.Add( ZDOVars.s_despawnInDay);
        list.Add( ZDOVars.s_dodgeinv);
        list.Add( ZDOVars.s_done);
        list.Add( ZDOVars.s_drops);
        list.Add( ZDOVars.s_durability);
        list.Add( ZDOVars.s_eitr);
        list.Add( ZDOVars.s_emote);
        list.Add( ZDOVars.s_emoteID);
        list.Add( ZDOVars.s_emoteOneshot);
        list.Add( ZDOVars.s_enabled);
        list.Add( ZDOVars.s_escape);
        list.Add( ZDOVars.s_eventCreature);
        list.Add( ZDOVars.s_follow);
        list.Add( ZDOVars.s_forward);
        list.Add( ZDOVars.s_fuel);
        list.Add( ZDOVars.s_growStart);
        list.Add( ZDOVars.s_hairColor);
        list.Add( ZDOVars.s_hairItem);
        list.Add( ZDOVars.s_haveSaddleHash);
        list.Add( ZDOVars.s_haveTargetHash);
        list.Add( ZDOVars.s_health);
        list.Add( ZDOVars.s_helmetItem);
        list.Add( ZDOVars.s_hitDir);
        list.Add( ZDOVars.s_hitPoint);
        list.Add( ZDOVars.s_hooked);
        list.Add( ZDOVars.s_hue);
        list.Add( ZDOVars.s_huntPlayer);
        list.Add( ZDOVars.s_inBed);
        list.Add( ZDOVars.s_inUse);
        list.Add( ZDOVars.s_inWater);
        list.Add( ZDOVars.s_initVel);
        list.Add( ZDOVars.s_isBlockingHash);
        list.Add( ZDOVars.s_item);
        list.Add( ZDOVars.s_item0);
        list.Add( ZDOVars.s_itemPrefab);
        list.Add( ZDOVars.s_itemStack);
        list.Add( ZDOVars.s_items);
        list.Add( ZDOVars.s_landed);
        list.Add( ZDOVars.s_lastAttack);
        list.Add( ZDOVars.s_lastSpawn);
        list.Add( ZDOVars.s_lastTime);
        list.Add( ZDOVars.s_leftBackItem);
        list.Add( ZDOVars.s_leftBackItemVariant);
        list.Add( ZDOVars.s_leftItem);
        list.Add( ZDOVars.s_leftItemVariant);
        list.Add( ZDOVars.s_legItem);
        list.Add( ZDOVars.s_level);
        list.Add( ZDOVars.s_liquidData);
        list.Add( ZDOVars.s_location);
        list.Add( ZDOVars.s_lookTarget);
        list.Add( ZDOVars.s_locked);
        list.Add( ZDOVars.s_lovePoints);
        list.Add( ZDOVars.s_maxHealth);
        list.Add( ZDOVars.s_maxInstances);
        list.Add( ZDOVars.s_modelIndex);
        list.Add( ZDOVars.s_noise);
        list.Add( ZDOVars.s_offset);
        list.Add( ZDOVars.s_owner);
        list.Add( ZDOVars.s_ownerName);
        list.Add( ZDOVars.s_patrol);
        list.Add( ZDOVars.s_patrolPoint);
        list.Add( ZDOVars.s_permitted);
        list.Add( ZDOVars.s_pickable);
        list.Add( ZDOVars.s_picked);
        list.Add( ZDOVars.s_pickedTime);
        list.Add( ZDOVars.s_piece);
        list.Add( ZDOVars.s_plantTime);
        list.Add( ZDOVars.s_played);
        list.Add( ZDOVars.s_playerID);
        list.Add( ZDOVars.s_playerName);
        list.Add( ZDOVars.s_plays);
        list.Add( ZDOVars.s_pose);
        list.Add( ZDOVars.s_pregnant);
        list.Add( ZDOVars.s_product);
        list.Add( ZDOVars.s_pvp);
        list.Add( ZDOVars.s_quality);
        list.Add( ZDOVars.s_queued);
        list.Add( ZDOVars.s_randomSkillFactor);
        list.Add( ZDOVars.s_relPosHash);
        list.Add( ZDOVars.s_relRotHash);
        list.Add( ZDOVars.s_rightBackItem);
        list.Add( ZDOVars.s_rightItem);
        list.Add( ZDOVars.s_rodOwner);
        list.Add( ZDOVars.s_rooms);
        list.Add( ZDOVars.s_rudder);
        list.Add( ZDOVars.s_saturation);
        list.Add( ZDOVars.s_scaleHash);
        list.Add( ZDOVars.s_scaleScalarHash);
        list.Add( ZDOVars.s_seAttrib);
        list.Add( ZDOVars.s_seed);
        list.Add( ZDOVars.s_shoulderItem);
        list.Add( ZDOVars.s_shoulderItemVariant);
        list.Add( ZDOVars.s_shownAlertMessage);
        list.Add( ZDOVars.s_skinColor);
        list.Add( ZDOVars.s_sleeping);
        list.Add( ZDOVars.s_spawnAmount);
        list.Add( ZDOVars.s_spawnOre);
        list.Add( ZDOVars.s_spread);
        list.Add( ZDOVars.s_stack);
        list.Add( ZDOVars.s_stamina);
        list.Add( ZDOVars.s_startTime);
        list.Add( ZDOVars.s_state);
        list.Add( ZDOVars.s_stealth);
        list.Add( ZDOVars.s_support);
        list.Add( ZDOVars.s_tag);
        list.Add( ZDOVars.s_tagauthor);
        list.Add( ZDOVars.s_tameLastFeeding);
        list.Add( ZDOVars.s_tameTimeLeft);
        list.Add( ZDOVars.s_tamed);
        list.Add( ZDOVars.s_tamedName);
        list.Add( ZDOVars.s_tamedNameAuthor);
        list.Add( ZDOVars.s_targets);
        list.Add( ZDOVars.s_text);
        list.Add( ZDOVars.s_tiltrot);
        list.Add( ZDOVars.s_timeOfDeath);
        list.Add( ZDOVars.s_triggered);
        list.Add( ZDOVars.s_type);
        list.Add( ZDOVars.s_user);
        list.Add( ZDOVars.s_utilityItem);
        list.Add( ZDOVars.s_value);
        list.Add( ZDOVars.s_variant);
        list.Add( ZDOVars.s_velHash);
        list.Add( ZDOVars.s_wakeup);
        list.Add( ZDOVars.s_weaponLoaded);
        list.Add( ZDOVars.s_worldTimeHash);
        list.Add( ZDOVars.s_visual);
        list.Add( ZDOVars.s_terrainModifierTimeCreated);
        list.Add( ZDOVars.s_spawnPoint);
        list.Add( ZDOVars.s_SpawnPoint__DontUse);
        list.Add( ZDOVars.s_spawnTime);
        list.Add( ZDOVars.s_SpawnTime__DontUse);
        list.Add( ZDOVars.s_spawn_time__DontUse);
        list.Sort();
        return list;
    }
    /*static readonly KeyValuePair<int, int> s_zdoidUser = new KeyValuePair<int, int>("user_u".GetStableHashCode(), "user_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_zdoidRodOwner = new KeyValuePair<int, int>("RodOwner_u".GetStableHashCode(), "RodOwner_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_sessionCatchID = new KeyValuePair<int, int>("CatchID_u".GetStableHashCode(), "CatchID_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_toRemoveTarget = new KeyValuePair<int, int>("target_u".GetStableHashCode(), "target_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_toRemoveSpawnID = new KeyValuePair<int, int>("spawn_id_u".GetStableHashCode(), "spawn_id_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_toRemoveParentID = new KeyValuePair<int, int>("parent_id_u".GetStableHashCode(), "parent_id_i".GetStableHashCode());*/
}