using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

namespace Argo.DataAnalysis;

public class ZDOInfo
{
    public readonly Dictionary<int, string> HashToName;
    public readonly List<int>               Hashes;
    public static string GetName(int hash) {
        if (instance != null && instance.HashToName.TryGetValue(hash, out var name))
        {
            return name;
        }
        return "";
    }
    private ZDOInfo() {
        HashToName = GetNames();
        Hashes     = MakeHashList();
    }

    private static ZDOInfo? instance;
    public static  ZDOInfo  Instance { get => instance ??= new ZDOInfo(); }

    private static Type GetZdoType(Player player, int hash) {
        ZDOID      zdoID = player.GetZDOID();
        float      s_floats;
        Vector3    s_vec3;
        Quaternion s_quats;
        int        s_ints;
        long       s_longs;
        string     s_strings;
        byte[]     s_byteArrays;
        Type       type = typeof(void);
        return type; // todo, might not be possible
    }
    private static Dictionary<int, string> GetNames() {
        Dictionary<int, string> dict = new Dictionary<int, string>();
        
        dict.Add    (ZDOVars.s_accTime, "accTime");
        dict.Add    (ZDOVars.s_addedDefaultItems, "addedDefaultItems");
        dict.Add    (ZDOVars.s_aggravated, "aggravated");
        dict.Add    (ZDOVars.s_alert, "alert");
        dict.Add    (ZDOVars.s_aliveTime, "alive_time");
        dict.Add    (ZDOVars.s_ammo, "ammo");
        dict.Add    (ZDOVars.s_ammoType, "ammoType");
        dict.Add    (ZDOVars.s_attachJointHash, "attachJoint");
        dict.Add    (ZDOVars.s_author, "author");
        dict.Add    (ZDOVars.s_authorDisplayName, "authorPlatformDisplayName");
        dict.Add    (ZDOVars.s_bait, "Bait");
        dict.Add    (ZDOVars.s_bakeTimer, "bakeTimer");
        dict.Add    (ZDOVars.s_baseValue, "baseValue");
        dict.Add    (ZDOVars.s_beardItem, "BeardItem");
        dict.Add    (ZDOVars.s_bodyAVelHash, "body_avel");
        dict.Add    (ZDOVars.s_bodyVelHash, "body_vel");
        dict.Add    (ZDOVars.s_bodyVelocity, "BodyVelocity");
        dict.Add    (ZDOVars.s_catchID, "catchID");
        dict.Add    (ZDOVars.s_chestItem, "ChestItem");
        dict.Add    (ZDOVars.s_content, "Content");
        dict.Add    (ZDOVars.s_crafterID, "crafterID");
        dict.Add    (ZDOVars.s_crafterName, "crafterName");
        dict.Add    (ZDOVars.s_creator, "creator");
        dict.Add    (ZDOVars.s_creatorName, "creatorName");
        dict.Add    (ZDOVars.s_data, "data");
        dict.Add    (ZDOVars.s_dataCount, "dataCount");
        dict.Add    (ZDOVars.s_dead, "dead");
        dict.Add    (ZDOVars.s_debugFly, "DebugFly");
        dict.Add    (ZDOVars.s_despawnInDay, "DespawnInDay");
        dict.Add    (ZDOVars.s_dodgeinv, "dodgeinv");
        dict.Add    (ZDOVars.s_done, "done");
        dict.Add    (ZDOVars.s_drops, "drops");
        dict.Add    (ZDOVars.s_durability, "durability");
        dict.Add    (ZDOVars.s_eitr, "eitr");
        dict.Add    (ZDOVars.s_emoteOneshot, "emote_oneshot");
        dict.Add    (ZDOVars.s_emote, "emote");
        dict.Add    (ZDOVars.s_emoteID, "emoteID");
        dict.Add    (ZDOVars.s_enabled, "enabled");
        dict.Add    (ZDOVars.s_escape, "escape");
        dict.Add    (ZDOVars.s_eventCreature, "EventCreature");
        dict.Add    (ZDOVars.s_follow, "follow");
        dict.Add    (ZDOVars.s_forward, "forward");
        dict.Add    (ZDOVars.s_fuel, "fuel");
        dict.Add    (ZDOVars.s_growStart, "GrowStart");
        dict.Add    (ZDOVars.s_hairColor, "HairColor");
        dict.Add    (ZDOVars.s_hairItem, "HairItem");
        dict.Add    (ZDOVars.s_haveSaddleHash, "HaveSaddle");
        dict.Add    (ZDOVars.s_haveTargetHash, "haveTarget");
        dict.Add    (ZDOVars.s_health, "health");
        dict.Add    (ZDOVars.s_helmetItem, "HelmetItem");
        dict.Add    (ZDOVars.s_hitDir, "HitDir");
        dict.Add    (ZDOVars.s_hitPoint, "HitPoint");
        dict.Add    (ZDOVars.s_hooked, "hooked");
        dict.Add    (ZDOVars.s_hue, "Hue");
        dict.Add    (ZDOVars.s_huntPlayer, "huntplayer");
        dict.Add    (ZDOVars.s_inBed, "inBed");
        dict.Add    (ZDOVars.s_initVel, "InitVel");
        dict.Add    (ZDOVars.s_inUse, "InUse");
        dict.Add    (ZDOVars.s_inWater, "inWater");
        dict.Add    (ZDOVars.s_isBlockingHash, "IsBlocking");
        dict.Add    (ZDOVars.s_item, "item");
        dict.Add    (ZDOVars.s_item0, "item0");
        dict.Add    (ZDOVars.s_itemPrefab, "itemPrefab");
        dict.Add    (ZDOVars.s_items, "items");
        dict.Add    (ZDOVars.s_itemStack, "itemStack");
        dict.Add    (ZDOVars.s_landed, "landed");
        dict.Add    (ZDOVars.s_lastAttack, "lastAttack");
        dict.Add    (ZDOVars.s_lastSpawn, "LastSpawn");
        dict.Add    (ZDOVars.s_lastTime, "lastTime");
        dict.Add    (ZDOVars.s_worldTimeHash, "lastWorldTime");
        dict.Add    (ZDOVars.s_leftBackItem, "LeftBackItem");
        dict.Add    (ZDOVars.s_leftBackItemVariant, "LeftBackItemVariant");
        dict.Add    (ZDOVars.s_leftItem, "LeftItem");
        dict.Add    (ZDOVars.s_leftItemVariant, "LeftItemVariant");
        dict.Add    (ZDOVars.s_legItem, "LegItem");
        dict.Add    (ZDOVars.s_level, "level");
        dict.Add    (ZDOVars.s_liquidData, "LiquidData");
        dict.Add    (ZDOVars.s_location, "location");
        dict.Add    (ZDOVars.s_locked, "Locked");
        dict.Add    (ZDOVars.s_lookTarget, "LookTarget");
        dict.Add    (ZDOVars.s_lovePoints, "lovePoints");
        dict.Add    (ZDOVars.s_maxHealth, "max_health");
        dict.Add    (ZDOVars.s_maxInstances, "MaxInstances");
        dict.Add    (ZDOVars.s_modelIndex, "ModelIndex");
        dict.Add    (ZDOVars.s_noise, "noise");
        dict.Add    (ZDOVars.s_offset, "offset");
        dict.Add    (ZDOVars.s_owner, "owner");
        dict.Add    (ZDOVars.s_ownerName, "ownerName");
        dict.Add    (ZDOVars.s_patrol, "patrol");
        dict.Add    (ZDOVars.s_patrolPoint, "patrolPoint");
        dict.Add    (ZDOVars.s_permitted, "permitted");
        dict.Add    (ZDOVars.s_pickable, "pickable");
        dict.Add    (ZDOVars.s_pickedTime, "picked_time");
        dict.Add    (ZDOVars.s_picked, "picked");
        dict.Add    (ZDOVars.s_pickedUp, "pickedUp");
        dict.Add    (ZDOVars.s_piece, "piece");
        dict.Add    (ZDOVars.s_plantTime, "plantTime");
        dict.Add    (ZDOVars.s_played, "played");
        dict.Add    (ZDOVars.s_playerID, "playerID");
        dict.Add    (ZDOVars.s_playerName, "playerName");
        dict.Add    (ZDOVars.s_plays, "plays");
        dict.Add    (ZDOVars.s_pose, "pose");
        dict.Add    (ZDOVars.s_pregnant, "pregnant");
        dict.Add    (ZDOVars.s_product, "product");
        dict.Add    (ZDOVars.s_pvp, "pvp");
        dict.Add    (ZDOVars.s_quality, "quality");
        dict.Add    (ZDOVars.s_queued, "queued");
        dict.Add    (ZDOVars.s_randomSkillFactor, "RandomSkillFactor");
        dict.Add    (ZDOVars.s_relPosHash, "relPos");
        dict.Add    (ZDOVars.s_relRotHash, "relRot");
        dict.Add    (ZDOVars.s_rightBackItem, "RightBackItem");
        dict.Add    (ZDOVars.s_rightItem, "RightItem");
        dict.Add    (ZDOVars.s_rodOwner, "rodOwner");
        dict.Add    (ZDOVars.s_roomData, "roomData");
        dict.Add    (ZDOVars.s_rooms, "rooms");
        dict.Add    (ZDOVars.s_rudder, "rudder");
        dict.Add    (ZDOVars.s_saturation, "Saturation");
        dict.Add    (ZDOVars.s_scaleHash, "scale");
        dict.Add    (ZDOVars.s_scaleScalarHash, "scaleScalar");
        dict.Add    (ZDOVars.s_seAttrib, "seAttrib");
        dict.Add    (ZDOVars.s_seed, "seed");
        dict.Add    (ZDOVars.s_shoulderItem, "ShoulderItem");
        dict.Add    (ZDOVars.s_shoulderItemVariant, "ShoulderItemVariant");
        dict.Add    (ZDOVars.s_shownAlertMessage, "ShownAlertMessage");
        dict.Add    (ZDOVars.s_skinColor, "SkinColor");
        dict.Add    (ZDOVars.s_sleeping, "sleeping");
        dict.Add    (ZDOVars.s_spawn_time__DontUse, "spawn_time");
        dict.Add    (ZDOVars.s_spawnAmount, "SpawnAmount");
        dict.Add    (ZDOVars.s_spawnOre, "SpawnOre");
        dict.Add    (ZDOVars.s_spawnPoint, "spawnpoint");
        dict.Add    (ZDOVars.s_SpawnPoint__DontUse, "SpawnPoint");
        dict.Add    (ZDOVars.s_spawnTime, "spawntime");
        dict.Add    (ZDOVars.s_SpawnTime__DontUse, "SpawnTime");
        dict.Add    (ZDOVars.s_spread, "spread");
        dict.Add    (ZDOVars.s_stack, "stack");
        dict.Add    (ZDOVars.s_stamina, "stamina");
        dict.Add    (ZDOVars.s_startTime, "StartTime");
        dict.Add    (ZDOVars.s_state, "state");
        dict.Add    (ZDOVars.s_stealth, "Stealth");
        dict.Add    (ZDOVars.s_support, "support");
        dict.Add    (ZDOVars.s_tag, "tag");
        dict.Add    (ZDOVars.s_tagauthor, "tagauthor");
        dict.Add    (ZDOVars.s_tamed, "tamed");
        dict.Add    (ZDOVars.s_tamedName, "TamedName");
        dict.Add    (ZDOVars.s_tamedNameAuthor, "TamedNameAuthor");
        dict.Add    (ZDOVars.s_tameLastFeeding, "TameLastFeeding");
        dict.Add    (ZDOVars.s_tameTimeLeft, "TameTimeLeft");
        dict.Add    (ZDOVars.s_targets, "targets");
        dict.Add    (ZDOVars.s_TCData, "TCData");
        dict.Add    (ZDOVars.s_terrainModifierTimeCreated,      "terrainModifierTimeCreated");
        dict.Add    (ZDOVars.s_text, "text");
        dict.Add    (ZDOVars.s_tiltrot, "tiltrot");
        dict.Add    (ZDOVars.s_timeOfDeath, "timeOfDeath");
        dict.Add    (ZDOVars.s_triggered, "triggered");
        dict.Add    (ZDOVars.s_type, "type");
        dict.Add    (ZDOVars.s_user, "user");
        dict.Add    (ZDOVars.s_utilityItem, "UtilityItem");
        dict.Add    (ZDOVars.s_value, "Value");
        dict.Add    (ZDOVars.s_variant, "variant");
        dict.Add    (ZDOVars.s_velHash, "vel");
        dict.Add    (ZDOVars.s_visual, "visual");
        dict.Add    (ZDOVars.s_wakeup, "wakeup");
        dict.Add    (ZDOVars.s_weaponLoaded, "WeaponLoaded");
        dict.Add    (ZDOVars.s_worldLevel, "worldLevel");
        return dict;
    }
    private static List<int> MakeHashList() {
        List<int> list = [];
        list.Add(ZDOVars.s_accTime);
        list.Add(ZDOVars.s_addedDefaultItems);
        list.Add(ZDOVars.s_aggravated);
        list.Add(ZDOVars.s_alert);
        list.Add(ZDOVars.s_aliveTime);
        list.Add(ZDOVars.s_ammo);
        list.Add(ZDOVars.s_ammoType);
        list.Add(ZDOVars.s_attachJointHash);
        list.Add(ZDOVars.s_author);
        list.Add(ZDOVars.s_authorDisplayName);
        list.Add(ZDOVars.s_bait);
        list.Add(ZDOVars.s_bakeTimer);
        list.Add(ZDOVars.s_baseValue);
        list.Add(ZDOVars.s_beardItem);
        list.Add(ZDOVars.s_bodyAVelHash);
        list.Add(ZDOVars.s_bodyVelHash);
        list.Add(ZDOVars.s_bodyVelocity);
        list.Add(ZDOVars.s_catchID);
        list.Add(ZDOVars.s_chestItem);
        list.Add(ZDOVars.s_content);
        list.Add(ZDOVars.s_crafterID);
        list.Add(ZDOVars.s_crafterName);
        list.Add(ZDOVars.s_creator);
        list.Add(ZDOVars.s_creatorName);
        list.Add(ZDOVars.s_data);
        list.Add(ZDOVars.s_dataCount);
        list.Add(ZDOVars.s_dead);
        list.Add(ZDOVars.s_debugFly);
        list.Add(ZDOVars.s_despawnInDay);
        list.Add(ZDOVars.s_dodgeinv);
        list.Add(ZDOVars.s_done);
        list.Add(ZDOVars.s_drops);
        list.Add(ZDOVars.s_durability);
        list.Add(ZDOVars.s_eitr);
        list.Add(ZDOVars.s_emoteOneshot);
        list.Add(ZDOVars.s_emote);
        list.Add(ZDOVars.s_emoteID);
        list.Add(ZDOVars.s_enabled);
        list.Add(ZDOVars.s_escape);
        list.Add(ZDOVars.s_eventCreature);
        list.Add(ZDOVars.s_follow);
        list.Add(ZDOVars.s_forward);
        list.Add(ZDOVars.s_fuel);
        list.Add(ZDOVars.s_growStart);
        list.Add(ZDOVars.s_hairColor);
        list.Add(ZDOVars.s_hairItem);
        list.Add(ZDOVars.s_haveSaddleHash);
        list.Add(ZDOVars.s_haveTargetHash);
        list.Add(ZDOVars.s_health);
        list.Add(ZDOVars.s_helmetItem);
        list.Add(ZDOVars.s_hitDir);
        list.Add(ZDOVars.s_hitPoint);
        list.Add(ZDOVars.s_hooked);
        list.Add(ZDOVars.s_hue);
        list.Add(ZDOVars.s_huntPlayer);
        list.Add(ZDOVars.s_inBed);
        list.Add(ZDOVars.s_initVel);
        list.Add(ZDOVars.s_inUse);
        list.Add(ZDOVars.s_inWater);
        list.Add(ZDOVars.s_isBlockingHash);
        list.Add(ZDOVars.s_item);
        list.Add(ZDOVars.s_item0);
        list.Add(ZDOVars.s_itemPrefab);
        list.Add(ZDOVars.s_items);
        list.Add(ZDOVars.s_itemStack);
        list.Add(ZDOVars.s_landed);
        list.Add(ZDOVars.s_lastAttack);
        list.Add(ZDOVars.s_lastSpawn);
        list.Add(ZDOVars.s_lastTime);
        list.Add(ZDOVars.s_worldTimeHash);
        list.Add(ZDOVars.s_leftBackItem);
        list.Add(ZDOVars.s_leftBackItemVariant);
        list.Add(ZDOVars.s_leftItem);
        list.Add(ZDOVars.s_leftItemVariant);
        list.Add(ZDOVars.s_legItem);
        list.Add(ZDOVars.s_level);
        list.Add(ZDOVars.s_liquidData);
        list.Add(ZDOVars.s_location);
        list.Add(ZDOVars.s_locked);
        list.Add(ZDOVars.s_lookTarget);
        list.Add(ZDOVars.s_lovePoints);
        list.Add(ZDOVars.s_maxHealth);
        list.Add(ZDOVars.s_maxInstances);
        list.Add(ZDOVars.s_modelIndex);
        list.Add(ZDOVars.s_noise);
        list.Add(ZDOVars.s_offset);
        list.Add(ZDOVars.s_owner);
        list.Add(ZDOVars.s_ownerName);
        list.Add(ZDOVars.s_patrol);
        list.Add(ZDOVars.s_patrolPoint);
        list.Add(ZDOVars.s_permitted);
        list.Add(ZDOVars.s_pickable);
        list.Add(ZDOVars.s_pickedTime);
        list.Add(ZDOVars.s_picked);
        list.Add(ZDOVars.s_pickedUp);
        list.Add(ZDOVars.s_piece);
        list.Add(ZDOVars.s_plantTime);
        list.Add(ZDOVars.s_played);
        list.Add(ZDOVars.s_playerID);
        list.Add(ZDOVars.s_playerName);
        list.Add(ZDOVars.s_plays);
        list.Add(ZDOVars.s_pose);
        list.Add(ZDOVars.s_pregnant);
        list.Add(ZDOVars.s_product);
        list.Add(ZDOVars.s_pvp);
        list.Add(ZDOVars.s_quality);
        list.Add(ZDOVars.s_queued);
        list.Add(ZDOVars.s_randomSkillFactor);
        list.Add(ZDOVars.s_relPosHash);
        list.Add(ZDOVars.s_relRotHash);
        list.Add(ZDOVars.s_rightBackItem);
        list.Add(ZDOVars.s_rightItem);
        list.Add(ZDOVars.s_rodOwner);
        list.Add(ZDOVars.s_roomData);
        list.Add(ZDOVars.s_rooms);
        list.Add(ZDOVars.s_rudder);
        list.Add(ZDOVars.s_saturation);
        list.Add(ZDOVars.s_scaleHash);
        list.Add(ZDOVars.s_scaleScalarHash);
        list.Add(ZDOVars.s_seAttrib);
        list.Add(ZDOVars.s_seed);
        list.Add(ZDOVars.s_shoulderItem);
        list.Add(ZDOVars.s_shoulderItemVariant);
        list.Add(ZDOVars.s_shownAlertMessage);
        list.Add(ZDOVars.s_skinColor);
        list.Add(ZDOVars.s_sleeping);
        list.Add(ZDOVars.s_spawn_time__DontUse);
        list.Add(ZDOVars.s_spawnAmount);
        list.Add(ZDOVars.s_spawnOre);
        list.Add(ZDOVars.s_spawnPoint);
        list.Add(ZDOVars.s_SpawnPoint__DontUse);
        list.Add(ZDOVars.s_spawnTime);
        list.Add(ZDOVars.s_SpawnTime__DontUse);
        list.Add(ZDOVars.s_spread);
        list.Add(ZDOVars.s_stack);
        list.Add(ZDOVars.s_stamina);
        list.Add(ZDOVars.s_startTime);
        list.Add(ZDOVars.s_state);
        list.Add(ZDOVars.s_stealth);
        list.Add(ZDOVars.s_support);
        list.Add(ZDOVars.s_tag);
        list.Add(ZDOVars.s_tagauthor);
        list.Add(ZDOVars.s_tamed);
        list.Add(ZDOVars.s_tamedName);
        list.Add(ZDOVars.s_tamedNameAuthor);
        list.Add(ZDOVars.s_tameLastFeeding);
        list.Add(ZDOVars.s_tameTimeLeft);
        list.Add(ZDOVars.s_targets);
        list.Add(ZDOVars.s_TCData);
        list.Add(ZDOVars.s_terrainModifierTimeCreated);
        list.Add(ZDOVars.s_text);
        list.Add(ZDOVars.s_tiltrot);
        list.Add(ZDOVars.s_timeOfDeath);
        list.Add(ZDOVars.s_triggered);
        list.Add(ZDOVars.s_type);
        list.Add(ZDOVars.s_user);
        list.Add(ZDOVars.s_utilityItem);
        list.Add(ZDOVars.s_value);
        list.Add(ZDOVars.s_variant);
        list.Add(ZDOVars.s_velHash);
        list.Add(ZDOVars.s_visual);
        list.Add(ZDOVars.s_wakeup);
        list.Add(ZDOVars.s_weaponLoaded);
        list.Add(ZDOVars.s_worldLevel);
        list.Sort();
        return list;
    }
    /*static readonly KeyValuePair<int, int> s_zdoidUser = new KeyValuePair<int, int>("user_u".GetStableHashCode(), "user_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_zdoidRodOwner = new KeyValuePair<int, int>("RodOwner_u".GetStableHashCode(), "RodOwner_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_sessionCatchID = new KeyValuePair<int, int>("CatchID_u".GetStableHashCode(), "CatchID_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_toRemoveTarget = new KeyValuePair<int, int>("target_u".GetStableHashCode(), "target_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_toRemoveSpawnID = new KeyValuePair<int, int>("spawn_id_u".GetStableHashCode(), "spawn_id_i".GetStableHashCode());
    static readonly KeyValuePair<int, int> s_toRemoveParentID = new KeyValuePair<int, int>("parent_id_u".GetStableHashCode(), "parent_id_i".GetStableHashCode());*/
}